version: '2'

services:
    de-kit-sensor-manager:
        build: ./
        image: de-kit-sensor-manager:1.0
        ports:
            - 8081:8081
        restart: always
        environment:
            - VIRTUAL_HOST=sensor-manager.jit-systems.de # example jitcloud.de
            - LETSENCRYPT_HOST=sensor-manager.jit-systems.de # should be the same as VIRTUAL_HOST
            - LETSENCRYPT_EMAIL=frostyandy2k@yahoo.com # example webmaster@agentur-murr.de
        networks:
            - nginx-proxy